apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devrancher.kenkohealth.in
  namespace: cattle-system
spec:
  secretName: devrancher.kenkohealth.in-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: devrancher.kenkohealth.in
  dnsNames:
  - devrancher.kenkohealth.in
